import { FaJava } from "react-icons/fa";
import {
  SiChartdotjs,
  SiDaisyui,
  SiDocker,
  SiEslint,
  SiFigma,
  SiGit,
  SiGithub,
  SiGooglecloud,
  SiGraphql,
  SiHibernate,
  SiJira,
  SiJsonwebtokens,
  SiNextdotjs,
  SiNpm,
  SiPostgresql,
  SiPostman,
  SiPrettier,
  SiReact,
  SiReactquery,
  SiRedis,
  SiSpring,
  SiTailwindcss,
  SiTrello,
  SiTypescript,
  SiVercel,
} from "react-icons/si";
import { MdOutlinePayment } from "react-icons/md";

const projectData = {
  rooms: {
    title: "A Full Stack Project (Back End and Front End)",
    descriptionList: [
      "This project is a web-based application designed with a mobile-first approach to ensure optimal user experience across devices. It offers two roles: user and tenant. Users can explore accommodations based on destination and availability, filter results by price, and even compare properties across different dates. If a property is unavailable on a selected date, the system clearly marks it. Meanwhile, tenants can manage property availability, adjust pricing dynamically based on specific dates, and track sales reports. A built-in review system allows users to leave feedback after their stay, with tenants having the option to respond.",
      "This project is a result of teamwork between me and Hizkia Sihombing, where we each focused on our own tasks and features.",
      "As for my part, I handled both the back-end and front-end development, focusing on features like:",
      "Smooth Transaction Flow: I implemented two payment systems: an automatic payment system using Midtrans' payment gateway, allowing users to pay via bank transfer and have their order status updated automatically, and a manual payment system, where users upload payment proofs to proceed. The system also manages automatic cancellations for late payments and ensures uploaded files meet size and format requirements.",
      "Tenant Management Tools: I developed features to help tenants confirm payments, send automated reminders, and manage cancellations with confirmation prompts for added security. Tenants can also view detailed sales reports and property availability insights.",
      "Review and Feedback System: I built a review feature that allows users to leave feedback post-stay and gives tenants the ability to respond, fostering better user-tenant engagement.",
    ],
    techStack: [
      { name: "Docker", icon: <SiDocker /> },
      { name: "ESLint", icon: <SiEslint /> },
      { name: "Figma", icon: <SiFigma /> },
      { name: "Git", icon: <SiGit /> },
      { name: "GitHub", icon: <SiGithub /> },
      { name: "Google Cloud", icon: <SiGooglecloud /> },
      { name: "GraphQL", icon: <SiGraphql /> },
      { name: "Hibernate", icon: <SiHibernate /> },
      { name: "Java", icon: <FaJava /> },
      { name: "Jira", icon: <SiJira /> },
      { name: "JWT", icon: <SiJsonwebtokens /> },
      { name: "Next.js", icon: <SiNextdotjs /> },
      { name: "NPM", icon: <SiNpm /> },
      { name: "Midtrans", icon: <MdOutlinePayment /> },
      { name: "PostgreSQL", icon: <SiPostgresql /> },
      { name: "Postman", icon: <SiPostman /> },
      { name: "Prettier", icon: <SiPrettier /> },
      { name: "React", icon: <SiReact /> },
      { name: "React Query", icon: <SiReactquery /> },
      { name: "Redis", icon: <SiRedis /> },
      { name: "Spring", icon: <SiSpring /> },
      { name: "TailwindCSS", icon: <SiTailwindcss /> },
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "Vercel", icon: <SiVercel /> },
    ],
    carousel: {
      projectsName: "rooms",
      imageNumber: 6,
    },
    cta: {
      description:
        "Let's dive in and simulate the process of booking a room at Rooms!",
      link: "https://rooms-hizkia-sihombings-projects.vercel.app/",
    },
    hero: {
      title: "Rooms",
      subtitle: "Property Renting Website",
      description:
        "Property Renting Web App helps users compare accommodation prices by date, influenced by holidays and manually set special dates.",
      imageUrl: "/projects/rooms/rooms-0.jpeg",
    },
  },
  kukivent: {
    title: "A Back-end Project",
    descriptionList: [
      "This project is an Event Management Platform designed to streamline the organization and participation in events. The platform supports two main types of events: Events and Exhibitions, catering to Exhibitors, Partners, Visitors, and Speakers.",
      "Exhibitors and Partners can host exhibitions, organize seminars with selected speakers, and showcase their products or services. Visitors can easily book tickets and access events of their choice, ensuring a smooth entry experience.",
      "This project was a collaboration between me and Muhammad Iqbal. While Iqbal focused on front-end development for user interaction, I took charge of the back-end system, ensuring stability and scalability.",
      "As the Back-End Developer, my responsibilities included:",
      "Database Design: I built a scalable database using PostgreSQL for efficient event and user data management.",
      "Core Back-End Development: Using Spring Boot and Hibernate, I implemented the platform's business logic and optimized server performance.",
      "Authentication and Authorization: I developed a secure system with role-based access for various user roles like Exhibitors, Partners, Visitors, and Speakers.",
      "Performance Optimization: Redis was integrated to enhance session management and caching, reducing server response times.",
      "Deployment: The project was deployed on Google Cloud Platform (GCP) for high availability and reliability.",
      "Event and Ticket Management: I implemented backend logic for event creation, ticket handling, and user role-specific operations.",
      "API Development: RESTful APIs were built to enable seamless communication between the front-end and back-end systems.",
    ],
    techStack: [
      { name: "Chart.js", icon: <SiChartdotjs /> },
      { name: "DaisyUI", icon: <SiDaisyui /> },
      { name: "Docker", icon: <SiDocker /> },
      { name: "ESLint", icon: <SiEslint /> },
      { name: "Figma", icon: <SiFigma /> },
      { name: "Git", icon: <SiGit /> },
      { name: "GitHub", icon: <SiGithub /> },
      { name: "Google Cloud", icon: <SiGooglecloud /> },
      { name: "Hibernate", icon: <SiHibernate /> },
      { name: "Java", icon: <FaJava /> },
      { name: "JWT", icon: <SiJsonwebtokens /> },
      { name: "Next.js", icon: <SiNextdotjs /> },
      { name: "NPM", icon: <SiNpm /> },
      { name: "PostgreSQL", icon: <SiPostgresql /> },
      { name: "Postman", icon: <SiPostman /> },
      { name: "Prettier", icon: <SiPrettier /> },
      { name: "React", icon: <SiReact /> },
      { name: "React Query", icon: <SiReactquery /> },
      { name: "Redis", icon: <SiRedis /> },
      { name: "Spring", icon: <SiSpring /> },
      { name: "TailwindCSS", icon: <SiTailwindcss /> },
      { name: "Trello", icon: <SiTrello /> },
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "Vercel", icon: <SiVercel /> },
    ],
    carousel: {
      projectsName: "kukivent",
      imageNumber: 5,
    },
    cta: {
      description: "Let's explore Kukivent!",
      link: "https://event-organizer-beta.vercel.app/",
    },
    hero: {
      title: "Kukivent",
      subtitle: "Event Management Platform",
      description:
        "Kukivent simplifies event organization with features for exhibitors, visitors, and partners, ensuring seamless ticket booking and event participation.",
      imageUrl: "/projects/kukivent/kukivent-0.jpeg",
    },
  },
  kukilabs: {
    title: "A Front-end Project",
    descriptionList: [
      "Kukilabs is a solo project: a Company Profile Website built from scratch to showcase the vision and services of a company inspired by Mekari. This project serves as a personal learning endeavor to explore front-end development and company profile design.",
      "Developed entirely with Next.js and TypeScript, this project represents a complete development lifecycle, including planning, implementation, and deployment.",
      "As a developer, I handled every aspect of the project, from building responsive UI to ensuring smooth functionality across devices.",
      "The website is deployed on Vercel, providing fast and reliable hosting for seamless user experience.",
      "Note: Kukilabs is inspired by Mekari, and some assets used in this project belong to Mekari. This project is strictly for personal learning purposes.",
    ],
    techStack: [
      { name: "DaisyUI", icon: <SiDaisyui /> },
      { name: "ESLint", icon: <SiEslint /> },
      { name: "Figma", icon: <SiFigma /> },
      { name: "Git", icon: <SiGit /> },
      { name: "GitHub", icon: <SiGithub /> },
      { name: "Next.js", icon: <SiNextdotjs /> },
      { name: "NPM", icon: <SiNpm /> },
      { name: "Prettier", icon: <SiPrettier /> },
      { name: "React", icon: <SiReact /> },
      { name: "TailwindCSS", icon: <SiTailwindcss /> },
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "Vercel", icon: <SiVercel /> },
    ],
    carousel: {
      projectsName: "kukilabs",
      imageNumber: 6,
    },
    cta: {
      description:
        "Explore Kukilabs to see how a company profile can come to life with sleek and modern design.",
      link: "https://kuki-code-challenge-2.vercel.app/",
    },
    hero: {
      title: "Kukilabs",
      subtitle: "Company Profile Website",
      description:
        "Kukilabs is a company profile website inspired by Mekari, showcasing services and values through a clean, modern design.",
      imageUrl: "/projects/kukilabs/kukilabs-0.jpeg",
    },
  },
};

export default projectData;
